### ISSUE TITLE
Only on appID entry possible

### ISSUE THREAD

**Issue by AndreasReitberger** [appodeal/appodeal-construct2-plugin#2]
I'm using one project to build to Android and iOS. Is there a way to add the fields

- appKey_Android
- appKey_iOS

instead of just one app key? Thank you!

**Comment by NazarKozak** [comment]
@AndreasReitberger hi! We will implement this feature in the next release.

**Comment by NazarKozak** [comment]
@AndreasReitberger we have released it already. Check new release on appodeal.com/sdk
